### ISSUE TITLE
Can't seem to get the extension to work (vscode on Debian 8.6)

### ISSUE THREAD

**Issue by karabaja4** [schneiderpat/aspnet-helper#2]
Hello,

I am trying to use your ASP.NET razor extension but I can't seem to get it to work on vscode + Debian 8.6.

Steps to reproduce:

mkdir hwapp && cd hwapp
dotnet new --type web
open the folder in vscode

Results: http://take.ms/3gWpU

Am I misconfiguring something? Please advise.

Regards,

Igor

**Comment by karabaja4** [comment]
P.S. I tested it on Windows 10 also, it works there.

**Comment by schneiderpat** [comment]
Hi,

i'm sorry to hear that! 
Can you check the version of your vs code installation? I am targeting the latest version 1.8.

Greets
Patrick

**Comment by karabaja4** [comment]
Both versions are 1.8.1 (the same version works on Windows and not on Debian).

http://take.ms/vDaww
http://take.ms/4mpCD

Regards,

Igor

**Comment by schneiderpat** [comment]
Hi,
I will try to reproduce this and let you know if I found a solution!

Greets
Patrick
