### ISSUE TITLE
Errors are displayed while using the extension

### ISSUE THREAD

**Issue by karabaja4** [schneiderpat/aspnet-helper#4]
Hello,

the extension generates the following errors:
https://paste.ubuntu.com/24002239/

ASP.NET Helper 0.6.1 / vscode 1.9.1 / Windows 10

Regards,

Igor

**Comment by SailleshPawar** [comment]
Any update on the issue?

**Comment by schneiderpat** [comment]
The latest builds didn't produce any errors. I published version 0.6.2 a few minutes ago. 
I hope I can get any feedback :)

**Comment by SailleshPawar** [comment]
Hi @schneiderpat i tested the extension i am facing below errors.
Please check the same.
 Message: Request textDocument/hover failed with message: Cannot read property 'type' of undefined
  Code: -32603

**Comment by SailleshPawar** [comment]
Hi @schneiderpat 
It works but I want to ask you do you have any dependency on  _ViewImports.cshtml file.
If I am building a project from scratch and I am not using tag helpers do I need to create the _ViewImports cshtml in order to use Intellisense on the view because it doesn't works than i am trying to figure out why?

**Comment by SailleshPawar** [comment]
I figured out if don't put 
@model ClasssName to the top line the IntelliSense won't work.
You can try the same.

Appreciate your hard work and will surely share and blog about it.

**Comment by schneiderpat** [comment]
Hi @SailleshPawar 
Let me know if you´re done with your blog! I would like to read it :D

**Comment by karabaja4** [comment]
I am still having issues :(

This is an example of one of my views. The property that the extension says it's missing does exist:
http://take.ms/QZXGg

Also intellisense for Model doesn't seem to work for me anymore:
http://take.ms/1mUl1

**Comment by SailleshPawar** [comment]
@karabaja4  Hi make sure you have updated to the latest update.

**Comment by karabaja4** [comment]
@SailleshPawar I am using latest - vscode 1.10.1 (released yesterday) and ASP:NET helper 0.6.2.

**Comment by SailleshPawar** [comment]
@karabaja4  Share the _ViewImports.cshtml code

**Comment by SailleshPawar** [comment]
@schneiderpat  It's dependent on _ViewImports.cshtml. I am trying to play with it, it seem like this to me. Can you please elaborate on the same.

**Comment by karabaja4** [comment]
`@using app.Portal.ViewModels.Admin
@using app.Portal.ViewModels.Controls
@using app.Portal.ViewModels.Databases
@using app.Portal.ViewModels.Home
@using app.Portal.ViewModels.Static
@using app.Portal.ViewModels.Controls.Utils
@using app.Base.Platform

@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"`

The model in my previous post is in namespace "app.Portal.ViewModels.Controls".

**Comment by SailleshPawar** [comment]
@karabaja4  latest version seems to be  0.6.0

**Comment by schneiderpat** [comment]
Are your models stored in a *ViewModels* or *Models* folder? 

Latest version is **0.6.2**

**Comment by karabaja4** [comment]
@schneiderpat Models are stored in _ViewModels_.

**Comment by schneiderpat** [comment]
Can you post your model?

**Comment by karabaja4** [comment]
@schneiderpat 

```
using Newtonsoft.Json;

namespace app.Portal.ViewModels.Controls
{
    public class IconAndLabelModel: IViewModel
    {
        [JsonIgnore]
        public string LeftIconClass { get; set; } = null;

        [JsonIgnore]
        public string Text { get; set; } = null;

        [JsonIgnore]
        public string RightIconClass { get; set; } = null;
    }
}
```

**Comment by schneiderpat** [comment]
The problem might be your interface or your default values. At the moment just simple classes are supported to provide IntelliSense.

**Comment by karabaja4** [comment]
@schneiderpat I get the same result if I remove the interface and default values.

I will try to put together a sample project for you so you can try and reproduce it from there.

**Comment by schneiderpat** [comment]
That would be the best! Thanks for your help at this issue! I´m sorry you´re facing it!

**Comment by SailleshPawar** [comment]
@karabaja4  That would be best.

**Comment by SailleshPawar** [comment]
Guyz are you using project.json or latest .csproj file?

**Comment by schneiderpat** [comment]
I´m using .csproj but project.json should be supported too

**Comment by SailleshPawar** [comment]
I updated VS code just now seems like IntelliSense for project.json  for dependencies is not coming. :(
extension is working fine no doubt with latest 0.6.2 (y)

**Comment by schneiderpat** [comment]
project.json is marked as deprecated, maybe they removed IntelliSense from it

**Comment by SailleshPawar** [comment]
@schneiderpat  Thanks for the update. Need to upgrade :D

**Comment by karabaja4** [comment]
I think I figured it out. This is the test project:

https://www.dropbox.com/s/myxn3l3cq3zsl09/app.zip?raw=1
(to start the project, run "dotnet restore" and "dotnet run" in app.portal folder)

You can see the problem in "MyView.cshtml" file.
In short, it seems that if the first entry in "_ViewImports.cshtml" is something that is not used in the view, the view displays an error.

Also please note that there seem to be two separate issues here: one is that the razor view linter complains about missing properties, and the other are errors when hovering over properties:

```
[Error - 21:20:38] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'type' of undefined
  Code: -32603 
```
